### ISSUE TITLE
Datatables Error in Accounting>References

### ISSUE THREAD

**Issue by imyunotme** [gjhuerte/sims#21] opened 2018-01-17 05:48 UTC

**Comment by gjhuerte** [comment] 2018-01-17 06:23
Duplicate of [https://github.com/gjhuerte/sims/issues/22](url)

**Comment by gjhuerte** [comment] 2018-01-17 06:23
Possible Duplicate of [https://github.com/gjhuerte/sims/issues/22](url)

**Comment by gjhuerte** [comment] 2018-01-17 06:24
Duplicate of [https://github.com/gjhuerte/sims/issues/22](url)

**Closed by gjhuerte** 2018-01-17 06:24 UTC
Labels: duplicate
